class Event {
  EventType? _eventType;
  int? _id;

  Event(EventType eventType) {
    _eventType = eventType;
  }

  EventType? get eventType => _eventType;

  int? get id => _id;

  set id(int? value) {
    _id = value;
  }
}

enum EventType {
  NEW_LOCATION_FETCHED,
  TIMER_START,
  TIMER_STOP,
  TIMER_PAUSE,
  TIMER_DEFAULT_TO_2_MIN,
  TIMER_DECREASE_TO_1_MIN,
  TIMER_DECREASE_TO_30_SECONDS,
  TIMER_DECREASE_TO_20_SECONDS,
  TIMER_DECREASE_TO_10_SECONDS,
  TIMER_DECREASE_TO_1_SECOND,
  REFRESH_HOME_PAGE,
  REFRESH_MAP_PAGE,
  REFRESH_VERIFICATION_PAGE,
  REFRESH_ACCOUNT_VERIFICATION_PAGE,
  REFRESH_PROFILE_SETUP_PAGE,
  REFRESH_BOOK_VALET_PAGE,
  REFRESH_BOOKING_HISTORY_PAGE,
  REFRESH_PROMOTION_CODE_PAGE,
  REFRESH_TRIP_END_PAGE,
  REFRESH_ALL_PAGES,
  REFRESH_FEED_CONTAINER,
  NAVIGATE_TO_HOME_PAGE,
  NAVIGATE_TO_RATE_VALET_PAGE
}
