module.exports = {
  AccessPattern: {
    USER_INFO: "userInfo",
    LOCATION_INFO: "locationInfo"
  },
  ServerEnum: {
    RESPONSE_CONNECTION_ERROR: "CONNECTION ERROR",
    RESPONSE_SUCCESS: "SUCCESS",
    RESPONSE_DATABASE_CONNECTION_ERROR: "DATABASE CONNECTION ERROR",
    RESPONSE_PASSWORD_MISMATCH: "PASSWORD MISMATCH",
    RESPONSE_EMAIL_MISMATCH: "EMAIL MISMATCH",
    RESPONSE_OTP_MISMATCH: "OTP MISMATCH",
    RESPONSE_EMAIL_TAKEN: "EMAIL TAKEN",
    RESPONSE_PHONE_TAKEN: "PHONE TAKEN",
    RESPONSE_INVALID_JWT_TOKEN: "INVALID JWT TOKEN",
    RESPONSE_ACCESS_DENIED: "ACCESS DENIED",
  }
};
