name: safe_walk_mobile
description: Strangers safety on the road

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  modal_bottom_sheet: ^2.0.0
  tuple: ^2.0.0
  shared_preferences: ^2.0.13
  image: ^3.1.1
  http: ^0.13.4
  permission_handler: ^8.3.0
  jiffy: ^5.0.0
  cached_network_image: ^3.2.0
  url_launcher: ^6.0.20
  package_info: ^2.0.2
  platform: ^3.1.0
  flutter_dash: ^0.0.1

  google_maps_flutter: ^2.1.1
  geolocator: ^8.1.1

  firebase_core: ^1.12.0
  firebase_storage: ^10.2.7
  firebase_auth: ^3.3.7
  firebase_messaging: ^11.2.6
  flutter_local_notifications: ^9.2.0
  intl: ^0.17.0

dev_dependencies:
  flutter_pdfview: ^1.2.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/safe_walk_logo.png"
  image_path_android: "assets/images/safe_walk_logo.png"
  # flutter pub get; flutter pub run flutter_launcher_icons:main

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/text/
    - assets/images/

